version: "3"

services:
  LandingPage:
    container_name: QLebraLanding
    image: nginx:1.14.2-alpine
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro